[dependencies]
"php/php-eh" = "=8.3.404-beta.6"

[fs]
"/app" = "app"
"/vendor" = "vendor"

[[command]]
name = "run"
module = "php/php-eh:php"
runner = "wasi"
[command.annotations.wasi]
main-args = ["-t", "/app", "-S", "localhost:8080"]
