ENUM UserRole {
  civilian // regular individual
  supervisor // decision factor
  authority // dude that cleans up the mess
}

TABLE User {
  id INTEGER PK
  email STRING UNIQUE
  password STRING // obviously hashed
  fname STRING
  lname STRING
  role UserRole
  createdAt DATETIME
  updatedAt DATETIME
}

TABLE LovedZone {
  idUser INTEGER [ref: > User.id]
  idZone INTEGER [ref: > Zone.id]

  // PRIMARY KEY (idUser, idZone)
}

TABLE Zone {
  id INTEGER PK
  name STRING
  city STRING
  country STRING
}

// null or done => decision maker
// pending pr inProgress => authority
ENUM PostStatus {
  pending // accepted by decision maker
  inProgress
  done
}

TABLE Post {
  id INTEGER PK
  description STRING
  status PostStatus
  idUser INTEGER [ref: > User.id]
  idZone INTEGER [ref: > Zone.id]
  address STRING
  createdAt DATETIME
  updatedAt DATETIME
}

ENUM MediaFormat {
  jpg
  png
  mp4
  webm
}

TABLE Media {
  id INTEGER PK
  name STRING // filename
  size INTEGER // in bytes
  source STRING // url
  format MediaFormat
  idPost INTEGER [ref: > Post.id]
}

ENUM TagColor {
  red
  orange
  yellow
  blue
  purple
  green
}

TABLE Tag {
  id INTEGER PK
  name STRING
  color TagColor
}

TABLE Mark {
  idTag INTEGER [ref: > Tag.id]
  idPost INTEGER [ref: > Post.id]
}
